version: '3'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 55dnBZ72x
      POSTGRES_DB: TestTaskBG
    ports:
      - "5432:5432"
      
  user-service:
    build: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:55dnBZ72x@database/TestTaskBG
    depends_on:
      - database

  post-service:
    build: ./post_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:55dnBZ72x@database/TestTaskBG
    depends_on:
      - database

  analyst-service:
    build: ./analyst_service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
